{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "puppetserver.postgres.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    {{- include "puppetserver.postgres.matchLabels" . | nindent 4 }}
{{- end }}
