apiVersion: v1
kind: ConfigMap
metadata:
  name: puppetdb-database-config
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
data:
  database.conf: |
    database: {
      subname: "//"${PUPPETDB_POSTGRES_HOSTNAME}":"${PUPPETDB_POSTGRES_PORT}"/"${PUPPETDB_POSTGRES_DATABASE}
      username: ${PUPPETDB_USER}
      password: ${PUPPETDB_PASSWORD}
      node-ttl: ${PUPPETDB_NODE_TTL}
      node-purge-ttl: ${PUPPETDB_NODE_PURGE_TTL}
      report-ttl: ${PUPPETDB_REPORT_TTL}
      maximum-pool-size: 50
    }
